// -*- C++ -*-
/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v2.5.7
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       https://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     https://www.dre.vanderbilt.edu/~schmidt/TAO.html
 **/


// TAO_IDL - Generated from
// /home/wang/ws/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_codegen.cpp:635

#ifndef _TAO_IDL_MESSENGERTYPESUPPORTS_TOYGCQ_CPP_
#define _TAO_IDL_MESSENGERTYPESUPPORTS_TOYGCQ_CPP_


#include "MessengerTypeSupportS.h"

#endif /* ifndef */

